# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# compile C with C:/Users/Oli/MinGW/bin/gcc.exe
C_FLAGS = -fno-strict-aliasing -Werror=pointer-arith -std=gnu99

C_DEFINES = -DGRAPHICS_API_OPENGL_43 -DPLATFORM_DESKTOP -D_CRT_SECURE_NO_WARNINGS

C_INCLUDES = @CMakeFiles/raylib.dir/includes_C.rsp

